import {
  AlertCircle,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  Clock,
  ExternalLink,
  FileEdit,
  FileText,
  Globe,
  Home,
  ImageIcon,
  Info,
  LayoutDashboard,
  Library,
  ListChecks,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Paperclip,
  Pencil,
  Plus,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Tags,
  Upload,
  UserPlus,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';
import type { SubmissionStatus } from '@/types';

export const ICON_NAV = 18;
export const ICON_INLINE = 16;

export const publicNavIcons: Record<string, LucideIcon> = {
  '/': Home,
  '/library': BookOpen,
  '/themes': Tags,
  '/narratives': MessageSquare,
  '/about': Info,
};

export const workspaceNavIcons: Record<string, LucideIcon> = {
  '/dashboard': LayoutDashboard,
  '/submit': Upload,
  '/members': Users,
  '/admin': ShieldCheck,
};

export const statusIcons: Record<SubmissionStatus, LucideIcon> = {
  draft: Pencil,
  submitted: Send,
  under_review: Search,
  approved: CheckCircle2,
  rejected: XCircle,
  changes_requested: AlertCircle,
  published: Globe,
};

export {
  AlertCircle,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  Clock,
  ExternalLink,
  FileEdit,
  FileText,
  Globe,
  Home,
  ImageIcon,
  Info,
  LayoutDashboard,
  Library,
  ListChecks,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Paperclip,
  Pencil,
  Plus,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Tags,
  Upload,
  UserPlus,
  Users,
  X,
  XCircle,
};
